# Site settings
title: Cantabile Piano
description: >
             Write an awesome description for your new site here. You can edit this
             line in _config.yml. It will appear in your document head meta (for
             Google search results) and in your feed.xml site description.
url: https://cantabile-piano.github.io
copyright: Yan-Yi Li

author:
  name: name
  bio: A short paragraph about you. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  avatar: avatar.jpg
  email: your-email@domain.com
  github: cantabile-piano
  twitter: username

disqus: ""
google-analytics: ""
carousel_slides: 4
words_per_minute: 200

# Build settings
sass:
  style: compressed
include: [_pages, _data]
exclude: [Gemfile, Gemfile.lock, LICENSE, Rakefile]
gems: [jekyll-paginate]
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"