# Site settings
title: Your awesome title
description: >
             Write an awesome description for your new site here. You can edit this
             line in _config.yml. It will appear in your document head meta (for
             Google search results) and in your feed.xml site description.
url: http://yoururl.com
copyright: Yan-Yi Li

author:
  name: name
  email: your-email@domain.com
  github: username
  twitter: username
  avatar: avatar.jpg

disqus: disqus-shortname
carousel-slides: 4

# Build settings
sass:
  style: compressed
include: ["_pages", "_data"]
gems: [jekyll-paginate]
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"