# Site settings
title: Cantabile Piano
description: >
             Piano teacher and music therapist based in London. From playing Hanon and Czerny, to working with children with learning disabilities using improvisation, this is my little journey of how my thinking has evolved.
url: https://cantabile-piano.github.io
github: cantabile-piano
copyright: Yan-Ling Li

author:
  name: Yan-Ling Li
  bio: Piano teacher and music therapist based in London.
  avatar: avatar.jpg
  email: cantabilepiano.london@gmail.com
  github: cantabile-piano
  twitter: ""

disqus: ""
google-analytics: ""
carousel_slides: 4
words_per_minute: 200

# Build settings
sass:
  style: compressed
include: [_pages, _data]
exclude: [Gemfile, Gemfile.lock, LICENSE, Rakefile]
gems: [jekyll-paginate, jekyll-admin]
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      searchable: true
      comments: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      searchable: false